version: "3"
services: 
  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    restart: always
    networks:
      - es-net
    environment:
      - xpack.security.enabled=false
      # - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - discovery.type=single-node
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    # expose:
    #   - 9200
  kibana:
    # image: docker.elastic.co/kibana/kibana:7.7.0
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    restart: always
    networks:
      - es-net
    environment:
      # SERVER_NAME: kibana
      # MONITORING_ENABLED: "true"
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge